name: Build & Publish

on:
  push:
    branches:
      - master
      - dev/dev

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest

    env:
      REPO_USER: ${{ secrets.REPO_USERNAME }}
      REPO_PASS: ${{ secrets.REPO_PASSWORD }}

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v7
        with:
          fetch-tags: true

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run jar and publish with Gradle Wrapper
        run: ./gradlew bundlerJar skanalyzer-core:publish -ProxymcUsername=${{ env.REPO_USER }} -ProxymcPassword=${{ env.REPO_PASS }}

      - name: Upload shell bundler artifact
        uses: actions/upload-artifact@v7
        with:
          name: skanalyzer-shell-bundler
          path: shell/build/distributions/skanalyzer-shell-bundler-*.jar
